spring:
  application:
    name: education-service-zuul

server:
  port: 8769

zuul:
  routes:
    user-server:
      path: /user/**
      serviceId: education-user-service

ribbon:
  ReadTimeout: 5000