spring:
  application:
    name: education-zuul

server:
  port: 8769

zuul:
  routes:
    service-user:
      path: /user/**
      serviceId: education-service-user
    service-system:
      path: /system/**
      serviceId: education-service-system
      strip-prefix: false

ribbon:
  ReadTimeout: 5000