spring:
  application:
    name: education-zuul

server:
  port: 8769

zuul:
  routes:
    user-server:
      path: /user/**
      serviceId: education-user-service
    web:
      prefix: false

ribbon:
  ReadTimeout: 5000