spring:
  application:
    name: education-zuul

server:
  port: 8769

zuul:
  routes:
    service-user:
      path: /api/user/**
      serviceId: education-service-user
    service-system:
      path: /api/system/**
      serviceId: education-service-system

ribbon:
  ReadTimeout: 5000